custom: ["rust-lang.org/funding", "rustnl.org/fund", "rustfoundation.org/get-involved"]
github:
- "spastorino"
- "rami3l"
- "m-ou-se"
- "joshtriplett"
- "flip1995"
- "djc"
- "lcnr"
- "chenyukang"
- "ZuseZ4"
- "WaffleLapkin"
- "Veykril"
- "Turbo87"
- "Nadrieril"
- "JonathanBrouwer"
- "BurntSushi"
